#!/bin/bash

## ====================================
## ===== Anon Surf [edit by uuep] =====
## ====================================

    ##############################

#=====================================
# Váriavies com as Cores
#=====================================
NONE="\033[0m" # Eliminar as Cores, deixar padrão)
NN="\033[0m" # Eliminar as Cores, deixar padrão)

## Efeito Negrito (bold) e cores
BK="\033[1;30m" # Bold+Black (Negrito+Preto)
BR="\033[1;31m" # Bold+Red (Negrito+Vermelho)
BG="\033[1;32m" # Bold+Green (Negrito+Verde)
BY="\033[1;33m" # Bold+Yellow (Negrito+Amarelo)
BB="\033[1;34m" # Bold+Blue (Negrito+Azul)
BM="\033[1;35m" # Bold+Magenta (Negrito+Vermelho Claro)
BC="\033[1;36m" # Bold+Cyan (Negrito+Ciano - Azul Claro)
BW="\033[1;37m" # Bold+White (Negrito+Branco)

## Cores Piscante
PCK="\033[5;30m" #Piscante+Black (Preto)
PCR="\033[5;31m" #Piscante+Red (Vermelho)
PCG="\033[5;32m" #Piscante+Green (Verde)
PCY="\033[5;33m" #Piscante+Yellow (Amarelo)
PCB="\033[5;34m" #Piscante+Blue (Azul)
PCM="\033[5;35m" #Piscante+Magenta (Vermelho Claro)
PCC="\033[5;36m" #Piscante+Cyan (Ciano - Azul Claro)
PCW="\033[5;37m" #Piscante+White (Branco)

#===========================================

# Destinations you don't want routed through Tor
TOR_EXCLUDE="192.168.0.0/16 172.16.0.0/12 10.0.0.0/8"

# The UID Tor runs as
# change it if, starting tor, the command 'ps -e | grep tor' returns a different UID
TOR_UID="debian-tor"

# Tor's TransPort
TOR_PORT="9040"

# Is resolvconf installed?
if [[ ! -z `dpkg -l |grep resolvconf` ]]; then 
	resolvconf_support=true;
else
	resolvconf_support=false;
fi


function init {
	echo -e " [$BG✔$BW] Encerrando aplicações de risco"
	killall -q chrome dropbox iceweasel skype icedove thunderbird firefox chromium xchat transmission deluge pidgin pidgin.orig
	
	echo -e " [$BG✔$BW] Limpando alguns elementos de cache perigosos"
	bleachbit -c adobe_reader.cache chromium.cache chromium.current_session chromium.history elinks.history emesene.cache epiphany.cache firefox.url_history flash.cache flash.cookies google_chrome.cache google_chrome.history  links2.history opera.cache opera.search_history opera.url_history &> /dev/null
}


function starti2p {
	echo -e " [$BG✔$BW] Iniciando Serviços de I2P"
sleep 2
	service tor stop

	# Modify DNS settings
	if [ "$resolvconf_support" = false ] 
	then
		cp /etc/resolv.conf /etc/resolv.conf.bak;
		touch /etc/resolv.conf;
		echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' > /etc/resolv.conf;
		echo -e " [$BG✔$BW] Modificando resolv.conf para usar localhost e acesso de DNS privado\n";
sleep 2
	else
		cp /etc/resolvconf/resolv.conf.d/head{,.bak};
		echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' >> /etc/resolvconf/resolv.conf.d/head;
		echo -e " [$BG✔$BW] Modificando resolvconf para usar localhost e acesso de DNS privado";
sleep 2
		resolvconf -u;
	fi
	sudo -u i2psvc i2prouter start
	sleep 2
	xdg-open 'http://127.0.0.1:7657/home'
}

function stopi2p {
	echo -e -n " [$BG✔$BW] Parando Serviços de I2P\n"
sleep 2
	sudo -u i2psvc i2prouter stop
	
	# restore DNS settings
	if [ "$resolvconf_support" = false ] 
	then
		if [ -e /etc/resolv.conf.bak ]; then
			rm /etc/resolv.conf
			cp /etc/resolv.conf.bak /etc/resolv.conf
		fi
	else
		mv /etc/resolvconf/resolv.conf.d/head{.bak,}
		resolvconf -u
	fi
}


function ip {
	clear
	echo -e "$BW ===================================="
	echo -e "$BW ====$BG Anon Surf $BW[$BB edit by uuep$BW ] ===="
	echo -e "$BW ===================================="
	echo -e " [$BG✔$BW] Meu ip é \n "
sleep 2
	curl "http://myexternalip.com/raw" # Had a few issues with FrozenBox giving me the wrong IP address
	echo  -e "\n"
	sleep 0
}

function start {
	clear
	echo -e "$BW ===================================="
	echo -e "$BW ====$BG Anon Surf $BW[$BB edit by uuep$BW ] ===="
	echo -e "$BW ====================================\n"
	# Make sure only root can run this script
	if [ $(id -u) -ne 0 ]; then
		echo -e " $BW[$BR!$NN] Esse script só pode ser iniciado como$BR ROOT$NN \n" >&2
sleep 2
		exit 1
	fi
	
	# Check defaults for Tor
	grep -q -x 'RUN_DAEMON="yes"' /etc/default/tor
	if [ $? -ne 0 ]; then
		echo -e "\n [$BW!$NN] Por favor, configure o arquivo /etc/default/tor e reinicie o serviço" >&2
sleep 2
		echo -e 'RUN_DAEMON="yes"'
		exit 1
	fi	
	
	# Kill IPv6 services
	echo -e "\n [$BG✔$BW] Parando Serviços IPv6"
sleep 2
	sed -i '/^.*\#kali-anonsurf$/d' /etc/sysctl.conf #delete lines containing #kali-anonsurf in /etc/sysctl.conf
	# add lines to sysctl.conf that will kill ipv6 services
	echo "net.ipv6.conf.all.disable_ipv6 = 1 #kali-anonsurf" >> /etc/sysctl.conf
	echo "net.ipv6.conf.default.disable_ipv6=1 #kali-anonsurf" >> /etc/sysctl.conf
	sysctl -p > /dev/null  # have sysctl reread /etc/sysctl.conf

	echo -e " [$BG✔$BW] Iniciando modo anônimo"
sleep 2
	
	if [ ! -e /var/run/tor/tor.pid ]; then
		echo -e " [$BR✘$BW] O Tor não está sendo executado no momento!"
sleep 2
		echo -e " [$BG✔$BW] Estamos executando Tor para você" >&2
sleep 2
		service network-manager force-reload > /dev/null 2>&1
		killall dnsmasq > /dev/null 2>&1
		killall nscd > /dev/null 2>&1	
		service tor start
		sleep 2
	fi
	if ! [ -f /etc/network/iptables.rules ]; then
		iptables-save > /etc/network/iptables.rules
		echo -e " [$BG✔$BW] Tabela de IP salva"
sleep 2
	fi
	
	iptables -F
	iptables -t nat -F
	
	if [ "$resolvconf_support" = false ] 
	then
		cp /etc/resolv.conf /etc/resolv.conf.bak
		touch /etc/resolv.conf
		echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' > /etc/resolv.conf
		echo -e " [$BG✔$BW] Modificando resolv.conf para usar Tor e Acesso de DNS Privado"
sleep 2
	else
		cp /etc/resolvconf/resolv.conf.d/head{,.bak}
                echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' >> /etc/resolvconf/resolv.conf.d/head
                echo -e " [$BG✔$BW] Modificando resolvconf para usar localhost e Acesso de DNS Privado" 
				resolvconf -u
sleep 2
	fi

	# set iptables nat
	iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
	iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 53
	iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 53
	iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports 53
	
	#resolve .onion domains mapping 10.192.0.0/10 address space
	iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports 9040
	iptables -t nat -A OUTPUT -p udp -d 10.192.0.0/10 -j REDIRECT --to-ports 9040
	
	#exclude local addresses
	for NET in $TOR_EXCLUDE 127.0.0.0/9 127.128.0.0/10; do
		iptables -t nat -A OUTPUT -d $NET -j RETURN
	done
	
	#redirect all other output through TOR
	iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
	iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $TOR_PORT
	iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports $TOR_PORT
	
	#accept already established connections
	iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
	
	#exclude local addresses
	for NET in $TOR_EXCLUDE 127.0.0.0/8; do
		iptables -A OUTPUT -d $NET -j ACCEPT
	done
	
	#allow only tor output
	iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
	iptables -A OUTPUT -j REJECT

	echo -e " [$BG✔$BW] Todo o tráfego foi redirecionado para o Tor"
sleep 2
	echo -e " [$BG✔$BW] Você está sob o tunel do$BG AnonSurf $NN"
}

#### Stop ####

function stop {
	# Tenha certeza que o script está sendo executado como Root
	if [ $(id -u) -ne 0 ]; then
		echo -e "\n $BW[$BR!$NN] Esse script só pode ser iniciado como$BR ROOT$NN \n" >&2
sleep 2
		exit 1
	fi
	clear
	echo -e "$BW ===================================="
	echo -e "$BW ====$BG Anon Surf $BW[$BB edit by uuep$BW ] ===="
	echo -e "$BW ====================================\n"
	echo -e " [$BR✘$BW] Parando o modo anônimo $NN"
sleep 2
	iptables -F
	iptables -t nat -F
	echo -e " [$BR✘$BW] Todas as Regras do IPTables foram deletadas $NN"
	sleep 2
	if [ -f /etc/network/iptables.rules ]; then
		iptables-restore < /etc/network/iptables.rules
		rm /etc/network/iptables.rules
		echo -e " [$BG✔$BW] As Regras do IPTables foram restauradas"
	fi
	sleep 2
	# restore DNS settings
	echo -e " [$BG✔$BW] Restaurando as configurações de DNS"
	sleep 2
	if [ "$resolvconf_support" = false ] 
	then
		if [ -e /etc/resolv.conf.bak ]; then
			rm /etc/resolv.conf
			cp /etc/resolv.conf.bak /etc/resolv.conf
		fi
	else
		mv /etc/resolvconf/resolv.conf.d/head{.bak,}
		resolvconf -u
sleep 2
	fi
	
	service tor stop
	
	echo -e " [$BG✔$BW] Reabilitando o serviço IPv6 $NN"
sleep 2
	# reenable IPv6 services
	sed -i '/^.*\#kali-anonsurf$/d' /etc/sysctl.conf #delete lines containing #kali-anonsurf in /etc/sysctl.conf
	sysctl -p # have sysctl reread /etc/sysctl.conf

	service network-manager force-reload > /dev/null 2>&1
	service nscd start > /dev/null 2>&1
	service dnsmasq start > /dev/null 2>&1
	
	echo -e " [$BG✔$BW] Modo Anônimo foi$BR Encerrado $NN"
	sleep 2
}

function change {
	service tor reload
	sleep 2
	echo -e "\n [$BG✔$BW] O modo anônimo foi$BB Reiniciado$NN"
	sleep 2
}

function status {
	clear
	echo -e "$BW ===================================="
	echo -e "$BW ====$BG Anon Surf $BW[$BB edit by uuep$BW ] ===="
	echo -e "$BW ====================================\n"
	service tor status
}

case "$1" in
	start)
		init
		start
	;;
	stop)
		init
		stop
	;;
	change)
		change
	;;
	status)
		status
	;;
	myip|ip)
		ip
	;;
	starti2p)
		starti2p
	;;
	stopi2p)
		stopi2p
	;;
	restart)
		$0 stop
		sleep 1
		$0 start
	;;
   *)
clear
	echo -e "$BW ===================================="
	echo -e "$BW ====$BG Anon Surf $BW[$BB edit by uuep$BW ] ===="
	echo -e "$BW ====================================\n"

echo -e "
	
$BY	Modo de uso: asf <comando>
		
$BG start$BW ────────╼ Inicia um sistema amplo com tunelagem TOR Proxy através do IPTables
$BR stop$BW ─────────╼ Reseta as configurações ogirinais do IPTables e volta para uma navegação limpa
$BB restart$BW ──────╼ Combinas as opções \"stop\" e \"start\"
$BB change$BW ───────╼ Troca a indentificação reiniciando o TOR
$BB status$BW ───────╼ Verifica se o AnonSurf está funcionando corretamente
$BB ip/myip$BW ──────╼ Exibe o seu endereço de IP atual
	
 ==== [ Recursos relacionados ao$BR I2P$BW ] ====
	
 starti2p	- Inicia o serviço i2p
 stopi2p	- Faz parar o serviço i2p
	
$NN" >&2
exit 1
;;
esac

echo -e $NN
exit 0
